package snakegame.fachwert.enums;

public enum PictureName
{
    HEADLEFT, HEADRIGHT, HEADUP, HEADDOWN, TITLE, SNAKEBODY, NORMALFOOD, FASTFOOD, INVERSEFOOD, INVINCIBLEFOOD, SLOWFOOD, SUPERFOOD, EWWFOOD, ORANGE, RED, YELLOW, BLUE, INDIGO, PURPLE, PINK, WOWUP, WOWRIGHT, WOWDOWN, WOWLEFT
}
